name: utils

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.19", "1.20", "1.21"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: go test -v ./...
